name: '🌍 Terraform Automation'

on:
  push:

env:
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}} # prod
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}} 
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🧩 HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: 🔑 Login to Azure
        id : az-login
        run : az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID  

      - name: 🏗️ Terraform 
        id: init
        run: |
            terraform init -input=false
            # terraform destroy -input=false -auto-approve
            terraform plan -out=tfplan -input=false
            terraform apply -input=false -auto-approve tfplan